### ISSUE TITLE
How to use a socks5 proxy?

### ISSUE THREAD

**Issue by paolobasso99** [asciimoo/morty#103]
I've seen in #70  that morty support using a socks5 proxy but I have not found any documentation on how to actually setup this proxy.
I have tried using: 

```
morty:
    container_name: morty
    image: dalf/morty
    restart: unless-stopped
    networks:
      - web_proxy
    command: -timeout 6 -ipv6 -socks5 ${MORTY_SOCKS5_USERNAME}:${MORTY_SOCKS5_PASSWORD}@${MORTY_SOCKS5_HOST}:${MORTY_SOCKS5_PORT}
    environment:
      - MORTY_KEY=${MORTY_KEY}
      - MORTY_ADDRESS=0.0.0.0:3000
    read_only: true
    cap_drop:
      - ALL
```
But it does not proxy the traffic.
Am i missing something?
